In [34]:
import numpy as np

with open("trees.txt") as f:
    trees = [[int(tree) for tree in list(line.strip())] for line in f.readlines()]
    
trees = np.array(trees)
print(trees)

[[2 1 3 ... 0 0 1]
 [0 3 2 ... 2 2 2]
 [2 1 1 ... 3 0 2]
 ...
 [3 2 3 ... 1 2 3]
 [0 2 0 ... 1 1 1]
 [0 0 0 ... 0 3 0]]


In [29]:
n_vis = 0
for (i, j), val in np.ndenumerate(trees):
#     print("coords:", i, j, "value:", val)
#     print(trees[:i, j])
#     print(trees[i, :j])
#     print(trees[i+1:, j])
#     print(trees[i, j+1:])
    
    up = val > np.max(trees[:i, j], initial=-1)
    left = val > np.max(trees[i, :j], initial=-1)
    down = val > np.max(trees[i+1:, j], initial=-1)
    right = val > np.max(trees[i, j+1:], initial=-1)
    if up or left or down or right:
        n_vis += 1

print(n_vis)

21


# Part 2

In [35]:
max_score = 0

for (i, j), val in np.ndenumerate(trees):
    # need to find first tree along a direction that is equal or taller than current tree
    # step along each direction until found? reverse up and left views since starting from inside of array
    # trees along the edges will always have a scenic score of 0 since multiplying by 0
    # therefore skip them
    
#     print("coords:", i, j, "value:", val)
    
    views = (trees[:i, j][::-1], trees[i, :j][::-1], trees[i+1:, j], trees[i, j+1:])  # up, left, down, right
    new_score = 1
    for view in views:
        n = 0
        for tree in view:
            n += 1
            if tree >= val:
                break
        new_score *= n
        if new_score == 0:  # only happens if n is still 0 i.e. on edge
            break
            
    max_score = max(new_score, max_score)

print(max_score)

536625
